customers_controllers:
    resource: 
        path: ../src/Customers/Controller/
        namespace: App\Customers\Controller
    type: attribute

artists_controllers:
    resource: 
        path: ../src/Artists/Infrastructure/Symfony/Controller/
        namespace: App\Artists\Infrastructure\Symfony\Controller
    type: attribute
